#!/usr/bin/env groovy

node {
    checkout scm

    final acrCredId = 'ACR_CREDS'
    final aksCredId = 'AKS_CREDS'
    final tenantCredId = 'TENANT_ID'

    // Define the workspace
    def workspace = pwd()
    def appImage

    stage('Build app image') {
        appImage = docker.build("app:${env.BUILD_ID}",
                                    "-f ${workspace}/app/Dockerfile ${workspace}/app")
    }

    stage('Push app image to ACR') {
        // Login to Azure Container Registry
        docker.withRegistry('https://bebyxregistry.azurecr.io', acrCredId) {
            // Push image
            appImage.push()
            appImage.push('latest')
        }
    }

    stage('Login into AZ as AKS User') {
        withCredentials([
                usernamePassword(
                        credentialsId: aksCredId,
                        usernameVariable: 'AKS_USERNAME',
                        passwordVariable: 'AKS_PASSWORD'),
                string(credentialsId: tenantCredId, variable: 'TENANT_ID')
        ]) {
            sh 'az login --service-principal -u $AKS_USERNAME -p $AKS_PASSWORD --tenant $TENANT_ID'
        }
    }

    stage('Get AKS creds') {
        sh 'az aks get-credentials --resource-group Artem-Candidate --name aks'
    }

    stage('Deploy app to k8s') {
        sh """
            cd ${workspace}/app/k8s
            kubectl apply -f deployment.yaml
            kubectl apply -f service.yaml
            kubectl apply -f ingress.yaml
        """
    }
}