#!/usr/bin/env groovy

node {
    checkout scm

    // Define the workspace
    def workspace = pwd()

    stage('Build') {
        def appImage = docker.build("app:${env.BUILD_ID}",
                                    "-f ${workspace}/app/Dockerfile ${workspace}/app")
    }
}